### ISSUE TITLE
Use a Heap Machine for Call-by-Need?

### ISSUE THREAD

**Issue by Saizan** [AndrasKovacs/smalltt#1]
As far as I understand the evaluator relies on Haskell's lazy semantics to implement CbN evaluation.

Would you recommend that even in a larger scale implementation?

I see mostly two drawbacks:

- The evaluator needs to be kept pure enough for for lazy eval to do the right thing. (e.g. adding an `Either Error` or `IO` layer to it would make it too strict.)
- The CbN sharing is not explicitly represented so it can't be used to speed-up any post-processing of the values.

An explicit heap would get around those, however it has larger constant factors when implemented in Haskell.

**Comment by ollef** [comment]
For what it's worth I also ran into this problem in Sixty, which borrows many ideas from smalltt, and I therefore use an explicit `Lazy` type: https://github.com/ollef/sixty/blob/722533c5d71871ca1aa6235fe79a53f33da99c36/src/Monad.hs#L23

**Comment by AndrasKovacs** [comment]
@Saizan 

I would definitely recommend it in large implementation. GHC RTS and native GHC thunks is by far the fastest cbn implementation which is available out-of-the-box; the only way to robustly beat it is to rewrite RTS from scratch like in Lean. Using native GHC thunks in the right way requires precise knowledge of thunking, forcing, strictness and low-level optimization, but IMO it's still more convenient to write optimized low-level Haskell than C++. 

> The evaluator needs to be kept pure enough

That's right, we cannot do `IO` read in evaluation, we need to either use immutable metacontexts or `unsafePerformIO`. `Either` in the evaluator is unnecessary, because it operates on well-formed syntax, so any error in evaluation is "impossible". I would generally avoid `Either`-based error handling and stick to `ReaderT IO` with `IO` exceptions, as they are almost zero-cost in GHC.

In the fastest implementations, side effects of evaluation would have to be manually and carefully handled in any case. In my implementation here, evaluation unsafely reads from a mutable metacontext, which yields extra efficiency, because when we force value thunks, we read from the *latest* metacontext, not from the metacontext at the time of thunk creation. However, this assumes monotonic metacontext update, and thus incompatible with *backtracking* elaboration. In a large-scale impl, I would likely do switching between backtrack-able and non-backtrack-able mode. IIRC there is something like this in Agda  as well.

> The CbN sharing is not explicitly represented so it can't be used to speed-up any post-processing of the values.

No post-processing should operate on full CbN values, we only quote/serialize/optimize local values from glued evaluation. The main point of glued eval is to separate values used for conversion checking from values which are serialized and post-processed. In my implementation the local values may have implicit unobserved sharing, but they are generally still small, and we do not pay any cost for observable sharing. 

@ollef 

> explicit Lazy type

Unfortunately `IORef` is much slower than native thunking, and it has a particularly bad impact on [GC performance](https://stackoverflow.com/questions/23462004/code-becomes-slower-as-more-boxed-arrays-are-allocated).

**Comment by ollef** [comment]
> Unfortunately IORef is much slower than native thunking, and it has a particularly bad impact on GC performance.

Yeah, I'm somewhat aware of the performance implications (because you've mentioned them before :smile: ), but since I want my elaborator to be monadic for other reasons (namely incremental compilation), I decided to do it with `IORef`s anyway. I might revisit that decision later, but right now I'm seeing bottlenecks in other parts of codebase, like the parser.

**Comment by Saizan** [comment]
> No post-processing should operate on full CbN values, we only quote/serialize/optimize local values from glued evaluation. The main point of glued eval is to separate values used for conversion checking from values which are serialized and post-processed.

By local values do you mean `Val` or `Tm` ?  

Suppose you had modules with interface files, would you store types and definitions as `Tm` there?

**Comment by AndrasKovacs** [comment]
@Saizan by local value I mean `Val` here. I would store `Tm` in interface files, and some parts of that may come from quoting `Val` with `vQuote`, but none of it would come from quoting `Glued`.
